# Generated by Django 6.0.4 on 2026-05-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudActulalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_documento', models.CharField(max_length=10)),
                ('Numero_ducumento', models.CharField(max_length=20)),
                ('Cod_asociado', models.CharField(max_length=30)),
                ('Correo_registrado', models.CharField(max_length=255)),
                ('P_nombre', models.CharField(max_length=30)),
                ('S_nombre', models.CharField(max_length=30)),
                ('P_apellido', models.CharField(max_length=30)),
                ('S_apellido', models.CharField(max_length=30)),
                ('Fecha_nacimiento', models.DateField()),
                ('Genero', models.CharField(max_length=10)),
                ('Celular', models.CharField(max_length=20)),
                ('Telefono_fijo', models.CharField(max_length=30)),
                ('Correo_nuevo', models.EmailField(max_length=255)),
                ('Departamento', models.CharField(max_length=50)),
                ('Ciudad', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=200)),
                ('Entidad_bancaria', models.CharField(max_length=50)),
                ('Tipo_cuenta', models.CharField(max_length=50)),
                ('Numero_cuenta', models.CharField(max_length=30)),
                ('Actividad_economica', models.CharField(max_length=200)),
                ('Ingreso_mesual', models.CharField(max_length=50)),
                ('Patrimonio', models.CharField(max_length=50)),
                ('Declarante_renta', models.CharField(max_length=5)),
                ('PeP', models.CharField(max_length=5)),
                ('Observaciones', models.TextField()),
                ('Fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('Numero_radicado', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Solicitud de Actualización',
                'verbose_name_plural': 'Solicitudes de Actualización',
                'db_table': 'Solicitudes_Actualizacion',
                'ordering': ['-Fecha_envio'],
            },
        ),
    ]
