# Generated by Django 6.0.4 on 2026-05-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortalAsociados', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudactulalizacion',
            old_name='Ingreso_mesual',
            new_name='Ingreso_mensual',
        ),
        migrations.RenameField(
            model_name='solicitudactulalizacion',
            old_name='Numero_ducumento',
            new_name='Numero_documento',
        ),
        migrations.AddField(
            model_name='solicitudactulalizacion',
            name='Estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('completada', 'Completada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
    ]
