# Generated by Django 6.0.5 on 2026-05-07 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortalAsociados', '0002_rename_ingreso_mesual_solicitudactulalizacion_ingreso_mensual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudactulalizacion',
            name='Actividad_economica',
        ),
        migrations.RemoveField(
            model_name='solicitudactulalizacion',
            name='Cod_asociado',
        ),
        migrations.RemoveField(
            model_name='solicitudactulalizacion',
            name='Entidad_bancaria',
        ),
        migrations.RemoveField(
            model_name='solicitudactulalizacion',
            name='Ingreso_mensual',
        ),
        migrations.RemoveField(
            model_name='solicitudactulalizacion',
            name='Numero_cuenta',
        ),
        migrations.RemoveField(
            model_name='solicitudactulalizacion',
            name='Tipo_cuenta',
        ),
        migrations.AlterModelTable(
            name='solicitudactulalizacion',
            table=None,
        ),
    ]
