# Generated by Django 6.0.5 on 2026-05-07 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortalAsociados', '0003_remove_solicitudactulalizacion_actividad_economica_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SolicitudActulalizacion',
            new_name='SolicitudActualizacion',
        ),
    ]
