# Generated by Django 6.0.5 on 2026-05-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortalAsociados', '0004_rename_solicitudactulalizacion_solicitudactualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudactualizacion',
            name='Fuentes_recursos',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='solicitudactualizacion',
            name='Fuentes_recursos_otro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
