# Generated by Django 6.0.5 on 2026-05-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortalAsociados', '0005_solicitudactualizacion_fuentes_recursos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudactualizacion',
            name='Estado',
        ),
        migrations.AddField(
            model_name='solicitudactualizacion',
            name='Año',
            field=models.IntegerField(default=2026),
            preserve_default=False,
        ),
    ]
