# Generated by Django 6.0.5 on 2026-05-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortalAsociados', '0006_remove_solicitudactualizacion_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudactualizacion',
            name='Fuentes_recursos',
            field=models.CharField(choices=[('salario', 'Salario'), ('otro', 'Otro')], default='no', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitudactualizacion',
            name='Fuentes_recursos_otro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
