# Generated by Django 6.0.5 on 2026-05-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortalAsociados', '0007_alter_solicitudactualizacion_fuentes_recursos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudactualizacion',
            name='Residencia_fiscal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='solicitudactualizacion',
            name='Residencia_fiscal_pais',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
