# Generated by Django 6.0.5 on 2026-05-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortalAsociados', '0008_solicitudactualizacion_residencia_fiscal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudactualizacion',
            name='Correo_nuevo',
        ),
        migrations.AlterField(
            model_name='solicitudactualizacion',
            name='Observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudactualizacion',
            name='S_apellido',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudactualizacion',
            name='S_nombre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudactualizacion',
            name='Telefono_fijo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
