# Generated by Django 6.0.5 on 2026-05-14 16:45

import fondo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Nombre interno para identificar el banner (no aparece en el sitio)', max_length=100)),
                ('imagen', models.ImageField(help_text='Imagen horizontal recomendada: 1200x500px. Formatos: JPG, PNG, WEBP', upload_to='banners/', validators=[fondo.models.validar_imagen_banner])),
                ('activo', models.BooleanField(default=True, help_text='Desactiva para ocultar sin borrar')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Menor número = aparece primero')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['orden'],
            },
        ),
    ]
