# Generated by Django 6.0.5 on 2026-05-27 16:24

import fondo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondo', '0002_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='imagen',
            field=models.ImageField(help_text='Imagen horizontal recomendada: 1774x887px. Formatos: JPG, PNG, WEBP', upload_to='banners/', validators=[fondo.models.validar_imagen_banner]),
        ),
    ]
