# Generated by Django 6.0.5 on 2026-05-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Tamaño recomendado: 400×300 px', upload_to='anuncios/', verbose_name='Imagen')),
                ('titulo', models.CharField(blank=True, max_length=100, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=200, verbose_name='Subtítulo')),
                ('enlace', models.URLField(blank=True, help_text="URL a donde va al hacer clic en la imagen o 'Ver más'", max_length=400, verbose_name='Enlace')),
                ('texto_boton', models.CharField(default='Ver más', max_length=60, verbose_name='Texto del botón')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
            ],
            options={
                'verbose_name': 'Anuncio',
                'verbose_name_plural': 'Anuncios',
                'ordering': ['orden'],
            },
        ),
    ]
