# Generated by Django 6.0.5 on 2026-05-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnuncioGrande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Tamaño recomendado: 800×600 px o más', upload_to='anuncios/grandes/', verbose_name='Imagen')),
                ('enlace', models.URLField(blank=True, help_text='Si lo llenas, la imagen será clickeable', max_length=400, verbose_name='Enlace (opcional)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
            ],
            options={
                'verbose_name': 'Anuncio grande',
                'verbose_name_plural': 'Anuncios grandes',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='AnuncioPequeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Tamaño recomendado: 400×300 px', upload_to='anuncios/pequenos/', verbose_name='Imagen')),
                ('titulo', models.CharField(blank=True, max_length=100, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=200, verbose_name='Subtítulo')),
                ('enlace', models.URLField(blank=True, max_length=400, verbose_name='Enlace')),
                ('texto_boton', models.CharField(default='Ver más', max_length=60, verbose_name='Texto del botón')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
            ],
            options={
                'verbose_name': 'Anuncio pequeño',
                'verbose_name_plural': 'Anuncios pequeños',
                'ordering': ['orden'],
            },
        ),
        migrations.DeleteModel(
            name='Anuncio',
        ),
    ]
