# Generated by Django 6.0.5 on 2026-06-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0002_anunciogrande_anunciopequeno_delete_anuncio'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnuncioFlotante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='anuncios/flotantes/')),
                ('enlace', models.URLField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='anunciogrande',
            options={'ordering': ['orden'], 'verbose_name': 'Anuncio Flotante', 'verbose_name_plural': 'Anuncios Flotantes'},
        ),
    ]
