# Generated by Django 6.0.5 on 2026-06-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0003_anuncioflotante_alter_anunciogrande_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anuncioflotante',
            options={'ordering': ['orden'], 'verbose_name': 'Anuncio Flotante', 'verbose_name_plural': 'Anuncios Flotantes'},
        ),
        migrations.AlterModelOptions(
            name='anunciogrande',
            options={'ordering': ['orden'], 'verbose_name': 'Anuncio grande', 'verbose_name_plural': 'Anuncios grandes'},
        ),
        migrations.AddField(
            model_name='anuncioflotante',
            name='fecha_limite',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
