# Generated by Django 6.0.5 on 2026-06-01 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0004_alter_anuncioflotante_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncioflotante',
            name='fecha_limite',
        ),
    ]
