# Generated by Django 6.0.5 on 2026-06-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0005_remove_anuncioflotante_fecha_limite'),
    ]

    operations = [
        migrations.AddField(
            model_name='anunciogrande',
            name='fecha_limite',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
