"""
Django settings for FondoEmpleados project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#n5r97l&1(*u7ahcw-4j)cfc72m8p%*j^=h4j=h+**2by54k#s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    ".trycloudflare.com",
    "127.0.0.1",
    "localhost",
    "app.montacargasamym.com"
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'fondo',
    'PortalAsociados',
    'anuncios',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'FondoEmpleados.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "anuncios.context_processors.anuncio_popup",# comfiiguracion para los anuncios 
            ],
        },
    },
]

WSGI_APPLICATION = 'FondoEmpleados.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


# aqui va la base de datos 
DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'Fondo_Empleados',
        'HOST': 'SQLSERVER', 
        'USER': 'desarrollo',
        'PASSWORD': '4ndr3$-31',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            'extra_params': 'Encrypt=no;TrustServerCertificate=yes;'
            
        },
    },
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/FondoEmpleados/fondo/static/'
STATIC_ROOT = r'E:\inetpub\wwwroot\PRUEBAS\FondoEmpleados\fondo\static'

#CONFIGURACION DEL CORREO DE OUTLLOOK
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.office365.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False                             
EMAIL_HOST_USER = 'practdesarrollo@montacargasamym.com'        
EMAIL_HOST_PASSWORD = 'Amym2026**'             
DEFAULT_FROM_EMAIL = 'FAMYM <tucorreo@famym.com.co>'


#ESTE ES LA CONFICURACION DE CLOUDFLARE
CSRF_TRUSTED_ORIGINS = [
    "https://*.trycloudflare.com",
]

#aqui se guardaran los archivos que esten subido 
MEDIA_URL  = "/FondoEmpleados/media/"
MEDIA_ROOT = BASE_DIR / "media"